language: node_js
node_js:
- node
cache: npm
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: main
env:
  global:
    secure: MncF1ZPK325jYQHKHFecfn7la9+XOcgA0EYcgo1elfpLRPV0Er3U6314h/jGYbyi2eAL1P7uaFBiCmPr4kAKCnJvuIgTFDo1Y0Z/MTGjB9qfklnDG35zs9eIrIBhlu2SuH/7XhWa2WS5LIkUu5FxNflytKLKD0ac7qCsjpAsR3glrCh/+nk3xg9YDtEDVws8ITHll4M2duOz4tXgvaJ+YJV2NaR+/peRrL+Uol3vtXYbeuXqQKFx/mH25UAfbF7QF9ABIZLcus3dQPhUSPUReGQlIZqhieNibIYE3Q4/1Z+f2U8ORnsLZ/fFDkUC7iqZLdm/NDVeHTZGrjhUk+EkijpYpDVkHHni+t4F+20E624Kq8pLgk6mff/9zWUusWnRXsBHuGAydROI3+aHkl8NKT/zRy/rsB7e4xXrZfTRKRYNS/7+eDMKJfo04KpooMMUEYJ3q0eFVPizWTNuHJ/G1grKCg2mjpU51x9SAJ5K6TxCKQKid2RkwD3WQqQxYDd/p9Zx2+N82IjfnSzLUpYZSCaoKDHVVsg5KtEdGPUecmy5YtfA69+0B027qPfCEUKuptFEVDA5Iosqtx4bsb8SpXd5yVpV8MJG9syOW2f/e1zsj6YR+ThyzaaDLsPgrwUjVw28YkhtoD6npODlmwcMfKMp2nfT3cPadBOQziHhNGc=
