export const points = {
  COMPONENT_COMMUNICATION: '组件通信',
  BINDING: '双向绑定',
  VUEX_ANG_GLOBAL: 'vuex vs 全局对象',
  PARENT_CHILD_HOOKS_SEQUENCE: '父子组件生命周期时序',
  SHOW_AND_IF: 'v-show vs v-if',
  COMPUTED_AND_WATCH: 'computed vs watch',
  COMPUTED_IMPLEMENT: 'computed实现',
  V_HTML: 'v-html的问题',
  REACTIVITY_THEROY: '响应式原理',
  DEFINE_PROPERTY_DISADVANTAGE: 'object.defineProperty缺点',
  ARRAY_DETECT: '检测数组变化',
  NEXT_TICK: 'nextTick',
  TEMPLATE_COMPILE: '模板编译',
  KEY_IN_LOOP: 'v-for中的key',
  FOR_WITH_IF: '为何v-for 和 v-if不建议一起使用',
  ROUTER_HASH_HISTORY: 'router的hash模式和history模式',
  DATA_FUNCTION: 'data为什么返回函数而不是对象',
  MVVM_THEROY: 'MVVM实现原理',
  VUE3_VUE2: 'vue3 vs vue2',
  VUE3_REACTIVITY: 'vue3的响应式原理',
  VUE2_DIFF_AND_VUE3_DIFF: 'vue2的diff和vue3的diff',
  PERORMANCE_OPTIMIZE: '性能优化'
}